### ISSUE TITLE
微信小程序支付的接口调试通过了吗？

### ISSUE THREAD

**Issue by qiuchengw** [milkbobo/gopay#1]
用了一下，在最后的支付的时候总是提示“支付签名验证错误”。
实在看不出哪儿出的问题，能否提供下小程序端的调用代码？

**Comment by qiuchengw** [comment]
好吧，我解决掉了。是因为WechatMiniProgramClient：：Pay 第二段签名没有传入appId。
这个也是要参与签名验证的。我自己fork了一个项目，已经改掉了这个问题。
但是因为golang的包路径问题，有太多无效的改动，我就不提pullrequest了。


仅需要在WechatMiniProgramClient::Pay 的第二段GenSign之前加一句：

`c["appId"] = this.AppID`

即可。

**Comment by milkbobo** [comment]
已修复，感谢你对本库的支持。
