### ISSUE TITLE
go get github.com/milkbobo/gopay

### ISSUE THREAD

**Issue by jackluo2012** [milkbobo/gopay#2]
大哥，go get 不下来呢？
➜  ~ go get github.com/milkbobo/gopay
# cd .; git clone https://github.com/fishedee/encoding /Users/jackluo/Works/golang/src/github.com/fishedee/encoding
Cloning into '/Users/jackluo/Works/golang/src/github.com/fishedee/encoding'...
remote: Repository not found.
fatal: repository 'https://github.com/fishedee/encoding/' not found
package github.com/fishedee/encoding: exit status 128

**Comment by milkbobo** [comment]
已修复，去掉第三方库的json方法，改用原生json方法
https://github.com/milkbobo/gopay/commit/1c02308a8cc2bd3984b47567fe80d89874af88db
